### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by SamGreenwood1** [mkoegel/speedtest4pi#2]
How do I verify that its running properly?

**Comment by sammer2001** [comment]
how do I determine what to set the hostname to?

**Comment by sammer2001** [comment]
How do I fix this error?

**Comment by mkoegel** [comment]
You can run the script manually 
`python3 speedtestdb.py`
It will give you the results on the commandline.
You can also check that the results end up in the database.
sqlite3 speedtest.db "select * from tests"

**Comment by mkoegel** [comment]
For the flask command remove the trailing /speedtest
It's only
`flask run -h x.x.x.x`

**Comment by mkoegel** [comment]
Please make sure to update the packages and remove speedtest-cli with
`pip3 uninstall speedtest-cli`
